### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by erxson** [melardev/XeytanJ-Async-RAT#5]
pyk

**Comment by erxdev** [comment]
When im adding "Main-Class: com.melardev.xeytanj.XeytanJClient" in META-INF
new error: 

C:\Users\fuckingslave\Desktop\XeytanJ-RAT-master\XeytanJ-RAT-master\XeytanJClient\target>java -jar xeytan-client-1.0-SNAPSHOT.jar
Archiver-Version Plexus Archiver
Manifest-Version 1.0
Created-By Apache Maven 3.3.9
Server-Port 3002
Connection-Key XeytaJServer
Enable-Persistence true
Built-By melardev
Build-Jdk 1.8.0_77
Server-Host localhost
Connection-Retry 780
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at com.melardev.xeytanj.logger.ConsoleLogger.<init>(ConsoleLogger.java:21)
        at com.melardev.xeytanj.XeytanJClient.<init>(XeytanJClient.java:58)
        at com.melardev.xeytanj.XeytanJClient.main(XeytanJClient.java:63)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 3 more
